import { DayData } from "../models.ts";
import {
  fmt0,
  fmt1,
  isoWeekStr,
  isoWeekYear,
  millisToMinutes,
  nextDay,
  nextDayYear,
  nonNapSleeps,
  prevDay,
  prevDayYear,
  recoveryColor,
  sportName,
  strainCategory,
} from "../render.ts";
import { formatDateUTC } from "../fetch.ts";

export function renderDaily(data: DayData): string {
  const date = data.date;
  const dateStr = formatDateUTC(date);
  const year = date.getUTCFullYear();

  const pd = prevDay(date);
  const nd = nextDay(date);
  const pdy = prevDayYear(date);
  const ndy = nextDayYear(date);
  const weekStr = isoWeekStr(date);
  const weekYear = isoWeekYear(date);

  const navPrev = `[[Health/WHOOP/${pdy}/daily-${pd}|← ${pd}]]`;
  const navWeek = `[[Health/WHOOP/${weekYear}/${weekStr}|Week ${weekStr}]]`;
  const navNext = `[[Health/WHOOP/${ndy}/daily-${nd}|${nd} →]]`;
  const nav = `${navPrev} | ${navWeek} | ${navNext}`;

  // Summary callout
  const recSummary = data.recovery
    ? `Recovery: **${fmt0(data.recovery.score.recovery_score)}%** (${recoveryColor(data.recovery.score.recovery_score)}) | `
    : "";
  const strainSummary = data.cycle
    ? `Strain: **${fmt1(data.cycle.score.strain)}** (${strainCategory(data.cycle.score.strain)})`
    : "";

  // Recovery section
  let recSection: string;
  if (data.recovery) {
    const r = data.recovery.score;
    recSection = `
| Metric | Value |
|--------|-------|
| Recovery Score | **${fmt0(r.recovery_score)}%** |
| HRV (RMSSD) | ${fmt1(r.hrv_rmssd_milli)} ms |
| Resting Heart Rate | ${fmt0(r.resting_heart_rate)} bpm |
| SpO₂ | ${fmt1(r.spo2_percentage)}% |
| Skin Temp | ${fmt1(r.skin_temp_celsius)}°C |
`.trim();
  } else {
    recSection = "*No recovery data for this day.*";
  }

  // Sleep section
  let sleepSection: string;
  if (data.sleeps.length > 0) {
    const parts: string[] = [];
    const nonNaps = nonNapSleeps(data.sleeps);
    for (const { index, sleep } of nonNaps) {
      const header = index === 0 ? "### Main Sleep" : `### Additional Sleep`;
      const ss = sleep.score.stage_summary;
      parts.push(`${header}
| Metric | Value |
|--------|-------|
| In Bed | ${millisToMinutes(ss.total_in_bed_time_milli)} |
| Awake | ${millisToMinutes(ss.total_awake_time_milli)} |
| Light Sleep | ${millisToMinutes(ss.total_light_sleep_time_milli)} |
| SWS (Deep) | ${millisToMinutes(ss.total_slow_wave_sleep_time_milli)} |
| REM | ${millisToMinutes(ss.total_rem_sleep_time_milli)} |
| Performance | ${fmt0(sleep.score.sleep_performance_percentage)}% |
| Efficiency | ${fmt0(sleep.score.sleep_efficiency_percentage)}% |
| Respiratory Rate | ${fmt1(sleep.score.respiratory_rate)} rpm |
| Disturbances | ${ss.disturbance_count} |`);
    }
    for (const s of data.sleeps) {
      if (s.nap) {
        parts.push(`### Nap
| Metric | Value |
|--------|-------|
| Duration | ${millisToMinutes(s.score.stage_summary.total_in_bed_time_milli)} |`);
      }
    }
    sleepSection = parts.join("\n\n");
  } else {
    sleepSection = "*No sleep data for this day.*";
  }

  // Strain section
  let strainSection: string;
  if (data.cycle) {
    const c = data.cycle.score;
    strainSection = `
| Metric | Value |
|--------|-------|
| Day Strain | **${fmt1(c.strain)}** (${strainCategory(c.strain)}) |
| Avg Heart Rate | ${c.average_heart_rate} bpm |
| Max Heart Rate | ${c.max_heart_rate} bpm |
| Calories (kJ) | ${fmt0(c.kilojoule)} kJ |
`.trim();
  } else {
    strainSection = "*No cycle/strain data for this day.*";
  }

  // Workouts section
  let workoutsSection: string;
  if (data.workouts.length > 0) {
    const parts: string[] = [];
    for (const w of data.workouts) {
      const name = w.sport_name || sportName(w.sport_id);
      const distRow =
        w.score.distance_meter > 0
          ? `| Distance | ${fmt1(w.score.distance_meter)}m |\n`
          : "";
      parts.push(`### ${name}

| Metric | Value |
|--------|-------|
| Strain | ${fmt1(w.score.strain)} |
| Avg HR | ${w.score.average_heart_rate} bpm |
| Max HR | ${w.score.max_heart_rate} bpm |
| Calories | ${fmt0(w.score.kilojoule)} kJ |
${distRow}`.trimEnd());
    }
    workoutsSection = parts.join("\n\n");
  } else {
    workoutsSection = "*No workouts recorded for this day.*";
  }

  return `---
type: note
tags:
  - fitness/whoop
  - daily-health
  - "${year}"
created: ${dateStr}
---

# WHOOP Daily — ${dateStr}

${nav}

> [!summary] Summary
> ${recSummary}${strainSummary}

---

## Recovery

${recSection}

---

## Sleep

${sleepSection}

---

## Strain

${strainSection}

---

## Workouts

${workoutsSection}

---

${nav}

*Generated by obsidian-whoop-plugin*
`;
}
