import { DayData, WeekStats } from "../models.ts";
import {
  fmt0,
  fmt1,
  millisToMinutes,
  nextWeekStr,
  nextWeekYear,
  prevWeekStr,
  prevWeekYear,
  primarySleep,
  recoveryColor,
  sportName,
} from "../render.ts";
import { formatDateUTC } from "../fetch.ts";

function dayOfWeek(d: Date): string {
  const days = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
  return days[d.getUTCDay()];
}

function monthDay(d: Date): string {
  const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  return `${months[d.getUTCMonth()]} ${String(d.getUTCDate()).padStart(2, "0")}`;
}

function longDate(d: Date): string {
  const days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
  const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  return `${days[d.getUTCDay()]}, ${months[d.getUTCMonth()]} ${String(d.getUTCDate()).padStart(2, "0")}`;
}

function dayLink(d: DayData): string {
  const year = d.date.getUTCFullYear();
  const dateStr = formatDateUTC(d.date);
  return `[[Health/WHOOP/${year}/daily-${dateStr}|${dayOfWeek(d.date)} ${monthDay(d.date)}]]`;
}

export function renderWeekly(stats: WeekStats): string {
  if (stats.days.length === 0) {
    return "*No data available for this week.*\n";
  }

  const firstDay = stats.days[0];
  const pw = prevWeekStr(firstDay.date);
  const nw = nextWeekStr(firstDay.date);
  const pwy = prevWeekYear(firstDay.date);
  const nwy = nextWeekYear(firstDay.date);

  const navPrev = `[[Health/WHOOP/${pwy}/${pw}|← Prev Week]]`;
  const navNext = `[[Health/WHOOP/${nwy}/${nw}|Next Week →]]`;
  const nav = `${navPrev} | ${navNext}`;

  // Daily breakdown table
  const breakdownRows = stats.days
    .map((d) => {
      const rec = d.recovery
        ? `${fmt0(d.recovery.score.recovery_score)}% (${recoveryColor(d.recovery.score.recovery_score)})`
        : "—";
      const hrv = d.recovery
        ? `${fmt1(d.recovery.score.hrv_rmssd_milli)} ms`
        : "—";
      const strain = d.cycle ? fmt1(d.cycle.score.strain) : "—";
      const ps = primarySleep(d.sleeps);
      const sleep = ps
        ? millisToMinutes(ps.score.stage_summary.total_in_bed_time_milli)
        : "—";
      return `| ${dayLink(d)} | ${rec} | ${hrv} | ${strain} | ${sleep} |`;
    })
    .join("\n");

  // Workout table
  const workoutRows: string[] = [];
  for (const d of stats.days) {
    for (const w of d.workouts) {
      const name = w.sport_name || sportName(w.sport_id);
      workoutRows.push(
        `| ${dayLink(d)} | ${name} | ${fmt1(w.score.strain)} | ${w.score.average_heart_rate} bpm | ${fmt0(w.score.kilojoule)} kJ |`
      );
    }
  }

  const workoutsSection =
    workoutRows.length > 0
      ? `| Date | Activity | Strain | Avg HR | Calories |
|------|----------|--------|--------|----------|
${workoutRows.join("\n")}`
      : "*No workouts recorded this week.*";

  // Highlights
  const bestLine = stats.bestDay
    ? `**Best Recovery Day:** ${longDate(stats.bestDay.date)}
${
  stats.bestDay.recovery
    ? `- Score: ${fmt0(stats.bestDay.recovery.score.recovery_score)}% | HRV: ${fmt1(stats.bestDay.recovery.score.hrv_rmssd_milli)} ms | RHR: ${fmt0(stats.bestDay.recovery.score.resting_heart_rate)} bpm`
    : ""
}`
    : "";

  const worstLine = stats.worstDay
    ? `**Worst Recovery Day:** ${longDate(stats.worstDay.date)}
${
  stats.worstDay.recovery
    ? `- Score: ${fmt0(stats.worstDay.recovery.score.recovery_score)}% | HRV: ${fmt1(stats.worstDay.recovery.score.hrv_rmssd_milli)} ms | RHR: ${fmt0(stats.worstDay.recovery.score.resting_heart_rate)} bpm`
    : ""
}`
    : "";

  const firstYear = firstDay.date.getUTCFullYear();

  return `---
type: note
tags:
  - fitness/whoop
  - weekly-health
created: ${stats.weekStart}
---

# WHOOP Weekly Summary — ${stats.weekStart} → ${stats.weekEnd}

${nav}

---

## Aggregate Stats

| Metric | Value |
|--------|-------|
| Avg Recovery | **${fmt0(stats.avgRecovery)}%** |
| Avg HRV | ${fmt1(stats.avgHRV)} ms |
| Avg RHR | ${fmt0(stats.avgRHR)} bpm |
| Avg Strain | ${fmt1(stats.avgStrain)} |
| Avg Sleep | ${millisToMinutes(stats.avgSleepMillis)} |
| Total Workouts | ${stats.totalWorkouts} |

---

## Recovery Distribution

| Color | Days |
|-------|------|
| 🟢 Green (67–100%) | ${stats.greenDays} |
| 🟡 Yellow (34–66%) | ${stats.yellowDays} |
| 🔴 Red (0–33%) | ${stats.redDays} |

---

## Daily Breakdown

| Date | Recovery | HRV | Strain | Sleep |
|------|----------|-----|--------|-------|
${breakdownRows}

---

## Workouts This Week

${workoutsSection}

---

## Highlights

${bestLine}

${worstLine}

---

${nav}

*Generated by obsidian-whoop-plugin*
`;
}
